### ISSUE TITLE
ubuntu18.04安装出现问题

### ISSUE THREAD

**Issue by fishwade** [feeluown/FeelUOwn#290]
All Rights Reserved., 'credits':     Thanks to CWI, CNRI, BeOpen.com, Zope Corporation and a cast of thousands
    for supporting Python development.  See www.python.org for more information., 'license': Type license() to see the full license text, 'help': Type help() for interactive help, or help(object) for help about object.}, 'QMetaObject': <class 'PyQt5.QtCore.QMetaObject'>, 'pyqtSlot': <built-in function pyqtSlot>, 'QOpenGLWidget': <class 'PyQt5.QtWidgets.QOpenGLWidget'>}
Traceback (most recent call last):
  File "/home/yuwei/.local/bin/feeluown", line 11, in <module>
    sys.exit(main())
  File "/home/yuwei/.local/lib/python3.6/site-packages/feeluown/__main__.py", line 237, in main
    run_forever(args, config)
  File "/home/yuwei/.local/lib/python3.6/site-packages/feeluown/__main__.py", line 202, in run_forever
    app = setup_app(args, config)
  File "/home/yuwei/.local/lib/python3.6/site-packages/feeluown/__main__.py", line 166, in setup_app
    app = create_app(config)
  File "/home/yuwei/.local/lib/python3.6/site-packages/feeluown/app.py", line 204, in create_app
    attach_attrs(app)
  File "/home/yuwei/.local/lib/python3.6/site-packages/feeluown/app.py", line 112, in attach_attrs
    from .ui import Ui
  File "/home/yuwei/.local/lib/python3.6/site-packages/feeluown/ui.py", line 32, in <module>
    from feeluown.widgets.mpv_widget import MpvOpenGLWidget
  File "/home/yuwei/.local/lib/python3.6/site-packages/feeluown/widgets/mpv_widget.py", line 3, in <module>
    from PyQt5.QtOpenGL import QGLContext
ModuleNotFoundError: No module named 'PyQt5.QtOpenGL'

![2019-08-27 17-26-04 的屏幕截图](https://user-images.githubusercontent.com/45041908/63759280-cb983680-c8ef-11e9-89ce-c3781d47e9b1.png)

**Comment by cosven** [comment]
```
sudo apt install python3-pyqt5.qtopengl
```
还需要安装 qtopengl 组件，文档漏了这个，我稍后在文档中补充一下。

**Comment by cosven** [comment]
我先关闭啦 ~ 如果安装还有问题的话，可以重新打开这个 issue。
