### ISSUE TITLE
ubuntu 18.04 使用 pip3 安装的版本遇到了一个ValueError

### ISSUE THREAD

**Issue by albertofwb** [feeluown/FeelUOwn#294]
```
python3 -m feeluown
[2019-09-23 12:00:23,305 ERROR plugin] : Failed to load module local
Traceback (most recent call last):
  File "/home/albert/.local/lib/python3.6/site-packages/feeluown/plugin.py", line 146, in _scan_entry_points
    module = entry_point.load()
  File "/home/albert/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/home/albert/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/albert/.local/lib/python3.6/site-packages/fuo_local/__init__.py", line 8, in <module>
    from .provider import provider
  File "/home/albert/.local/lib/python3.6/site-packages/fuo_local/provider.py", line 269, in <module>
    from .schemas import EasyMP3MetadataSongSchema
  File "/home/albert/.local/lib/python3.6/site-packages/fuo_local/schemas.py", line 8, in <module>
    class EasyMP3MetadataSongSchema(Schema):
  File "/home/albert/.local/lib/python3.6/site-packages/fuo_local/schemas.py", line 12, in EasyMP3MetadataSongSchema
    title = fields.Str(required=True, missing=DEFAULT_TITLE)
  File "/home/albert/.local/lib/python3.6/site-packages/marshmallow/fields.py", line 194, in __init__
    raise ValueError("'missing' must not be set for required fields.")
ValueError: 'missing' must not be set for required fields.
➜  python3.6 vim /home/albert/.local/lib/python3.6/site-packages/marshmallow/fields.py +194
```

**Comment by cosven** [comment]
应该是因为 `marshmallow` 这个包的版本过高导致的，marshmallow 8 月末发了个新版本（> 3.0）的版本，而 feeluown-local/feeluown-netease 等插件都是依赖 2.x 版本的 marshmallow。

简而言之：暂时的解决办法是用 pip3 安装 2.19 版本的 marshmallow `pip3 install 'marshmallow==2.19.5'`

长远来看， 我会让这些插件兼容两个版本的插件。

**Comment by albertofwb** [comment]
多谢，问题解决了。

我在做一个 跨平台的 pyqt 程序，想着看看有没有可以参考的程序，于是在google搜索 *哪些 pyqt5 程序*时，从知乎上看到了你这个作品的回答

有哪些设计较好的开源 PyQt/Qt/Qml 应用？

**Comment by cosven** [comment]
那我先关闭这个 issue 啦 ~
