### ISSUE TITLE
支持  show fuo://local/songs 命令

### ISSUE THREAD

**Issue by albertofwb** [feeluown/FeelUOwn#296]
echo show fuo://local/songs | nc localhost 23333

[2019-09-23 22:41:40,299 ERROR __init__] : handle cmd(action:show args:('fuo://local/songs',)) error
Traceback (most recent call last):
  File "/Users/albert/GitRepos/FeelUOwn/fuocore/cmds/__init__.py", line 63, in exec_cmd
    rv = handler.handle(cmd)
  File "/Users/albert/GitRepos/FeelUOwn/fuocore/cmds/show.py", line 40, in handle
    rv = router.dispatch(path, {'library': self.library})
  File "/Users/albert/GitRepos/FeelUOwn/fuocore/router.py", line 99, in dispatch
    rule, params, query = match(uri, self.rules)
  File "/Users/albert/GitRepos/FeelUOwn/fuocore/router.py", line 33, in match
    raise NotFound
fuocore.router.NotFound

**Comment by cosven** [comment]
现在应该是不支持 `show fuo://local/songs` 这个指令了，所以这里出现了 not found 错误。

但理论上最好是能给一个更加优雅的提示，而不是报错，这个点我后面修复一下。

**Comment by albertofwb** [comment]
show local songs + play local songs
使得终端播放音乐成为可能，为何要丢弃呢？

如果确认不再支持这个 feature 我尝试给完善下此处错误吧

**Comment by cosven** [comment]
之前考虑放弃主要有几个原因

1. 除了本地能一次性获取所有歌曲外，其它的（比如网易云，qq）都不能一次性获取所有歌曲
2. 如果歌曲很多的话，这个接口会输出很多很多行，感觉体验不太好

> 使得终端播放音乐成为可能，为何要丢弃呢？

嗯，确实是个需求... 我觉得可以单独给 `/local/songs` 加一个 handler，不考虑网易云（`/netease/songs`）等。比如 
```
show fuo://local/songs
# 下面这个可以以后实现，目前可能还不那么方便实现
play fuo://local/songs
```
