### ISSUE TITLE
Windows平台崩溃（无论是双击exe还是命令行启动）

### ISSUE THREAD

**Issue by Raibows** [feeluown/FeelUOwn#312]
**参照以下文档方式安装：**
![image](https://user-images.githubusercontent.com/37944786/73369843-3b22af80-42ee-11ea-9bb2-6d3a65119325.png)
**环境：**
win1909专业版
py3.6.5 venv
64bit
**描述**
无论是命令行feeluown还是双击在./venv/scripts/feeluown.exe均闪退崩溃。其中命令行中给出了报错如下
**报错**
$ feeluown
c:\users\raibows\desktop\venv\lib\site-packages\fuzzywuzzy\fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')
Traceback (most recent call last):
  File "c:\users\raibows\anaconda3\Lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\raibows\anaconda3\Lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Raibows\Desktop\venv\Scripts\feeluown.exe\__main__.py", line 7, in <module>
  File "c:\users\raibows\desktop\venv\lib\site-packages\feeluown\entry_points\run.py", line 43, in run
    return run_forever(args, config)
  File "c:\users\raibows\desktop\venv\lib\site-packages\feeluown\entry_points\run_app.py", line 50, in run_forever
    init_app(app)
  File "c:\users\raibows\desktop\venv\lib\site-packages\feeluown\app.py", line 182, in init_app
    app.coll_uimgr.initialize()
  File "c:\users\raibows\desktop\venv\lib\site-packages\feeluown\uimodels\collection.py", line 36, in initialize
    self._scan()
  File "c:\users\raibows\desktop\venv\lib\site-packages\feeluown\uimodels\collection.py", line 51, in _scan
    colls[1], colls[-1] = colls[-1], colls[1]
IndexError: list index out of range

**Comment by Elypha** [comment]
我这边有类似的问题
不过安装后第一次运行是正常的，关闭后第二次启动会报错
```
e:\dev\python37\lib\site-packages\fuzzywuzzy\fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')
Traceback (most recent call last):
  File "e:\dev\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "e:\dev\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "E:\Dev\Python37\Scripts\feeluown.exe\__main__.py", line 7, in <module>
  File "e:\dev\python37\lib\site-packages\feeluown\entry_points\run.py", line 43, in run
    return run_forever(args, config)
  File "e:\dev\python37\lib\site-packages\feeluown\entry_points\run_app.py", line 50, in run_forever
    init_app(app)
  File "e:\dev\python37\lib\site-packages\feeluown\app.py", line 182, in init_app
    app.coll_uimgr.initialize()
  File "e:\dev\python37\lib\site-packages\feeluown\uimodels\collection.py", line 36, in initialize
    self._scan()
  File "e:\dev\python37\lib\site-packages\feeluown\uimodels\collection.py", line 51, in _scan
    colls[1], colls[-1] = colls[-1], colls[1]
IndexError: list index out of range
```

**Comment by cosven** [comment]
`pip install "feeluown>=3.3.3" --upgrade`
升级到 3.3.3 版本可以解决。

**Comment by Elypha** [comment]
> `pip install "feeluown>=3.3.3" --upgrade`
> 升级到 3.3.3 版本可以解决。

辛苦了！我这边测试ok

**Comment by Raibows** [comment]
> `pip install "feeluown>=3.3.3" --upgrade`
> 升级到 3.3.3 版本可以解决。

问题解决。可以使用。建议尽快在doc中提及该方案，或者尽快修复。

**Comment by cosven** [comment]
> > `pip install "feeluown>=3.3.3" --upgrade`
> > 升级到 3.3.3 版本可以解决。
> 
> 问题解决。可以使用。建议尽快在doc中提及该方案，或者尽快修复。

嗯，这是昨天晚上修复的。新用户默认安装这个新版本。
