### ISSUE TITLE
Windows平台下创建桌面图标失败

### ISSUE THREAD

**Issue by 1235467** [feeluown/FeelUOwn#314]
根据官方文档执行得
python -m feeluown genicon
Traceback (most recent call last):
  File "C:\Users\hmh\AppData\Local\Programs\Python\Python37-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\hmh\AppData\Local\Programs\Python\Python37-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\hmh\AppData\Local\Programs\Python\Python37-32\lib\site-packages\feeluown\__main__.py", line 6, in <module>
    from feeluown.entry_points.run import run
  File "C:\Users\hmh\AppData\Local\Programs\Python\Python37-32\lib\site-packages\feeluown\entry_points\run.py", line 6, in <module>
    from fuocore.utils import is_port_used  # noqa: E402
  File "C:\Users\hmh\AppData\Local\Programs\Python\Python37-32\lib\site-packages\fuocore\__init__.py", line 2, in <module>
    from fuocore.player import (
  File "C:\Users\hmh\AppData\Local\Programs\Python\Python37-32\lib\site-packages\fuocore\player.py", line 175, in <module>
    from fuocore.mpvplayer import MpvPlayer  # noqa: F841, F401
  File "C:\Users\hmh\AppData\Local\Programs\Python\Python37-32\lib\site-packages\fuocore\mpvplayer.py", line 4, in <module>
    from mpv import (
  File "C:\Users\hmh\AppData\Local\Programs\Python\Python37-32\lib\site-packages\mpv.py", line 39, in <module>
    backend = CDLL('mpv-1.dll')
  File "C:\Users\hmh\AppData\Local\Programs\Python\Python37-32\lib\ctypes\__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] 找不到指定的模块。

**Comment by cosven** [comment]
看错误提示是说，你的系统没有找到 mpv-1.dll 文件。

你安装的时候，有进行这个操作么？
> 下载 [mpv-1.dll](https://github.com/cosven/FeelUOwn/releases/download/v3.0.1/mpv-1.dll) ， 将 mpv-1.dll 放入 C:\Windows\System32 目录。

https://feeluown.readthedocs.io/en/latest/quickstart.html#windows

**Comment by 1235467** [comment]
![image](https://user-images.githubusercontent.com/30495555/73590622-8f60a600-451f-11ea-98d7-a61be75855b0.png)

**Comment by 1235467** [comment]
这个操作做过

**Comment by cosven** [comment]
比较奇怪，我暂时也不确定问题在哪。目前只能用排除法来找问题，目前有一个猜想：mpv-1.dll 存在，但是有一些系统设置的问题，程序（Python）说找不到。

你可以在命令行运行这个命令试下么：`python3 -c "from ctypes import CDLL; CDLL('C:\Windows\System32\mpv-1.dll')"`
如果这个命令什么都没有输出，说明 **很大可能** 是某些系统设置不太正常。如果报错，则看具体的错误是什么。

**Comment by 1235467** [comment]
报错
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\hmh\AppData\Local\Programs\Python\Python37-32\lib\ctypes\__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] 找不到指定的模块。

**Comment by cosven** [comment]
你可以再运行一下下面两个语句么？

这条语句执行如果不报错，说明 ctypes 这个库没有问题，否则则有问题。
```sh
 python3 -c "from ctypes import CDLL; CDLL('C:\Windows\System32\mfcore.dll')"
```

这条语句如果执行输出 True，则 mpv-1.dll 确实存在。
```sh
python3 -c "import os; print(os.path.exists('C:\Windows\System32\mpv-1.dll'))"
```

**Comment by 1235467** [comment]
python -c "import os; print(os.path.exists('C:\Windows\System32\mpv-1.dll'))" False
python -c "from ctypes import CDLL; CDLL('C:\Windows\System32\mfcore.dll')"无输出

**Comment by cosven** [comment]
> python -c "import os; print(os.path.exists('C:\Windows\System32\mpv-1.dll'))" False
> python -c "from ctypes import CDLL; CDLL('C:\Windows\System32\mfcore.dll')"无输出

说明你的 `mpv-1.dll` 确实不存在，眼睛看到的可能是个假的。
1. 建议确认一下你的 mpv-1.dll 文件名是否有空格、或者中文字符等奇怪的东西
2. 确认一下 mpv-1.dll 文件是否有隐藏的后缀

另外，我又仔细看了一下你的截图，发现 mpv-1.dll 这个文件的图标和其它 dll 文件的图标有点不一样：它的右上角有蓝色的标记，而其它 dll 文件没有。说明这个文件确实存在蹊跷。

**Comment by 1235467** [comment]
蓝色标记是表示文件属性：压缩

**Comment by 1235467** [comment]
在取消其压缩属性后执行得
Traceback (most recent call last):
  File "C:\Users\hmh\AppData\Local\Programs\Python\Python37-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\hmh\AppData\Local\Programs\Python\Python37-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\hmh\AppData\Local\Programs\Python\Python37-32\lib\site-packages\feeluown\__main__.py", line 6, in <module>
    from feeluown.entry_points.run import run
  File "C:\Users\hmh\AppData\Local\Programs\Python\Python37-32\lib\site-packages\feeluown\entry_points\run.py", line 6, in <module>
    from fuocore.utils import is_port_used  # noqa: E402
  File "C:\Users\hmh\AppData\Local\Programs\Python\Python37-32\lib\site-packages\fuocore\__init__.py", line 2, in <module>
    from fuocore.player import (
  File "C:\Users\hmh\AppData\Local\Programs\Python\Python37-32\lib\site-packages\fuocore\player.py", line 175, in <module>
    from fuocore.mpvplayer import MpvPlayer  # noqa: F841, F401
  File "C:\Users\hmh\AppData\Local\Programs\Python\Python37-32\lib\site-packages\fuocore\mpvplayer.py", line 4, in <module>
    from mpv import (
  File "C:\Users\hmh\AppData\Local\Programs\Python\Python37-32\lib\site-packages\mpv.py", line 39, in <module>
    backend = CDLL('mpv-1.dll')
  File "C:\Users\hmh\AppData\Local\Programs\Python\Python37-32\lib\ctypes\__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 193] %1 不是有效的 Win32 应用程序。

**Comment by cosven** [comment]
看起来前进了一大步！

你的系统是 32 位的，还是 64 位的呀？你下载的是 mpv-1.dll 还是 mpv-1.i686.dll 呀？

**Comment by cosven** [comment]
看起来你的 Python 版本是个 32 位的，可以考虑下载 mpv-1.i686.dll 试试

参考这个 https://github.com/feeluown/FeelUOwn/releases
![image](https://user-images.githubusercontent.com/4962134/73839247-78d48a80-4850-11ea-9744-34bc365e7427.png)

**Comment by JIACHENG135** [comment]
我也碰到了这个bug。但是解决了，是mpv-1.dll的问题，把cosven提供的mpv-1.dll文件放入 System32底下就可以了。Surface Pro 6 - Windows 10 - 64 Bit/ Lenovo Y520 - Windows 10 - 64 Bit都运行成功了

**Comment by 1235467** [comment]
在下载mpv-1.i686.dll并改名后依然遇到问题
Traceback (most recent call last):
  File "C:\Users\hmh\AppData\Local\Programs\Python\Python37-32\Scripts\feeluown-script.py", line 11, in <module>
    load_entry_point('feeluown==3.3.8', 'console_scripts', 'feeluown')()
  File "C:\Users\hmh\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pkg_resources\__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "C:\Users\hmh\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pkg_resources\__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "C:\Users\hmh\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pkg_resources\__init__.py", line 2324, in load
    return self.resolve()
  File "C:\Users\hmh\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pkg_resources\__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "c:\users\hmh\appdata\local\programs\python\python37-32\lib\site-packages\feeluown-3.3.8-py3.7.egg\feeluown\__main__.py", line 6, in <module>
    from feeluown.entry_points.run import run
  File "c:\users\hmh\appdata\local\programs\python\python37-32\lib\site-packages\feeluown-3.3.8-py3.7.egg\feeluown\entry_points\run.py", line 6, in <module>
    from fuocore.utils import is_port_used  # noqa: E402
  File "c:\users\hmh\appdata\local\programs\python\python37-32\lib\site-packages\feeluown-3.3.8-py3.7.egg\fuocore\__init__.py", line 2, in <module>
    from fuocore.player import (
  File "c:\users\hmh\appdata\local\programs\python\python37-32\lib\site-packages\feeluown-3.3.8-py3.7.egg\fuocore\player.py", line 175, in <module>
    from fuocore.mpvplayer import MpvPlayer  # noqa: F841, F401
  File "c:\users\hmh\appdata\local\programs\python\python37-32\lib\site-packages\feeluown-3.3.8-py3.7.egg\fuocore\mpvplayer.py", line 5, in <module>
    from mpv import (
  File "c:\users\hmh\appdata\local\programs\python\python37-32\lib\site-packages\feeluown-3.3.8-py3.7.egg\mpv.py", line 39, in <module>
    backend = CDLL('mpv-1.dll')
  File "C:\Users\hmh\AppData\Local\Programs\Python\Python37-32\lib\ctypes\__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 193] %1 不是有效的 Win32 应用程序。

**Comment by 1235467** [comment]
![image](https://user-images.githubusercontent.com/30495555/74075625-4bedc680-4a4e-11ea-9d8b-f534b39c5d6d.png)

**Comment by cosven** [comment]
我有个疑问，你的文件下载下去为什么是个会带压缩标志呀？
然后你是怎么去除压缩标志的呢？

我怀疑是不是有什么安全软件对文件做了什么处理呐 =。=

另外就是你下载它的过程有没有做什么特殊处理？这个文件在好几个 windows 10 上都试过了，应该是没有问题的。

**Comment by cosven** [comment]
这个问题后来有解决或者找到原因吗？

**Comment by 1235467** [comment]
没有，已放弃

**Comment by hyq3351** [comment]
同样的问题，请问现在有解决办法了吗 @cosven

**Comment by cosven** [comment]
> 同样的问题，请问现在有解决办法了吗 @cosven

这个问题还没有解决，我在自己的电脑上复现不了。

另外，目前 64 位 Windows 在这里 https://github.com/feeluown/distribution/releases 下载 exe 文件。不过目前这个 exe 还有一个缺点：启动得花个几秒钟。

**Comment by cherryminami** [comment]
作者你好，我把mpv-1.i686.dll改名之后，复制、分别放在了windows system32 和system下面，然后就可以创建桌面图标了。在python官网下载的3.8.2 32位。我不是程序员，希望能帮到你。
![Capture](https://user-images.githubusercontent.com/62209533/76703296-ae2e8c80-66c8-11ea-82fd-0497b8ce7588.PNG)

**Comment by cosven** [comment]
简单总结一下这个 issue，根据 JIACHENG135 和 cherryminami 两位朋友提供的信息，以及我自己的测试情况

- 64 位系统 + 64 位 Python + mpv-1.dll 可以正常工作（cherryminami 提供的信息可以说明这一点）
- 32 位 Python + mpv-1.i686.dll 可以正常工作（cherryminami 提供的信息可以说明这一点）

**Comment by linyiyun** [comment]
mpv-1.dll 这个文件点进去404了，要去哪下啊？

**Comment by cosven** [comment]
https://github.com/feeluown/FeelUOwn/releases/download/untagged-a44abb7d9646ba3b734a/mpv-1.dll

这里可以下载 @linyiyun 

https://github.com/feeluown/FeelUOwn/releases
在这个页面

**Comment by 1235467** [comment]
这几天突然发现我之前在64位的系统上装了32位的python ，不管是64还是32位的dll均不生效

**Comment by cosven** [comment]
> 这几天突然发现我之前在64位的系统上装了32位的python ，不管是64还是32位的dll均不生效

理论上 64 位系统 + 32 位 Python + 32 位 DLL 是能工作的 🤔。

**Comment by cok3307788** [comment]
right , follow this issue, a 64-bit win7 with a 64-bit python and a 64-bit mpv-1.dll , then I got 
`C:\Users\Administrator>python -m feeluown genicon
Traceback (most recent call last):
  File "D:\Program Files\Python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\Program Files\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\Program Files\Python38\lib\site-packages\feeluown\__main__.py", line 6, in <module>
    from feeluown.entry_points.run import run
  File "D:\Program Files\Python38\lib\site-packages\feeluown\entry_points\run.py", line 16, in <module>
    from .base import create_config, setup_argparse  # noqa: E402
  File "D:\Program Files\Python38\lib\site-packages\feeluown\entry_points\base.py", line 7, in <module>
    from feeluown.app import App
  File "D:\Program Files\Python38\lib\site-packages\feeluown\app.py", line 28, in <module>
    from .version import VersionManager
  File "D:\Program Files\Python38\lib\site-packages\feeluown\version.py", line 4, in <module>
    from packaging import version
ModuleNotFoundError: No module named 'packaging'`
I have FINISH pip3 install , how to fix it?

**Comment by cosven** [comment]
> right , follow this issue, a 64-bit win7 with a 64-bit python and a 64-bit mpv-1.dll , then I got
> `C:\Users\Administrator>python -m feeluown genicon Traceback (most recent call last): File "D:\Program Files\Python38\lib\runpy.py", line 194, in _run_module_as_main return _run_code(code, main_globals, None, File "D:\Program Files\Python38\lib\runpy.py", line 87, in _run_code exec(code, run_globals) File "D:\Program Files\Python38\lib\site-packages\feeluown\__main__.py", line 6, in <module> from feeluown.entry_points.run import run File "D:\Program Files\Python38\lib\site-packages\feeluown\entry_points\run.py", line 16, in <module> from .base import create_config, setup_argparse # noqa: E402 File "D:\Program Files\Python38\lib\site-packages\feeluown\entry_points\base.py", line 7, in <module> from feeluown.app import App File "D:\Program Files\Python38\lib\site-packages\feeluown\app.py", line 28, in <module> from .version import VersionManager File "D:\Program Files\Python38\lib\site-packages\feeluown\version.py", line 4, in <module> from packaging import version ModuleNotFoundError: No module named 'packaging'`
> I have FINISH pip3 install , how to fix it?

Run `pip3 install packging` should fix the problem. This bug is fixed in master branch： https://github.com/feeluown/FeelUOwn/issues/488

**Comment by cok3307788** [comment]
> > right , follow this issue, a 64-bit win7 with a 64-bit python and a 64-bit mpv-1.dll , then I got
> > `C:\Users\Administrator>python -m feeluown genicon Traceback (most recent call last): File "D:\Program Files\Python38\lib\runpy.py", line 194, in _run_module_as_main return _run_code(code, main_globals, None, File "D:\Program Files\Python38\lib\runpy.py", line 87, in _run_code exec(code, run_globals) File "D:\Program Files\Python38\lib\site-packages\feeluown\__main__.py", line 6, in <module> from feeluown.entry_points.run import run File "D:\Program Files\Python38\lib\site-packages\feeluown\entry_points\run.py", line 16, in <module> from .base import create_config, setup_argparse # noqa: E402 File "D:\Program Files\Python38\lib\site-packages\feeluown\entry_points\base.py", line 7, in <module> from feeluown.app import App File "D:\Program Files\Python38\lib\site-packages\feeluown\app.py", line 28, in <module> from .version import VersionManager File "D:\Program Files\Python38\lib\site-packages\feeluown\version.py", line 4, in <module> from packaging import version ModuleNotFoundError: No module named 'packaging'`
> > I have FINISH pip3 install , how to fix it?
> 
> Run `pip3 install packging` should fix the problem. This bug is fixed in master branch： #488

放弃了，
`C:\Users\Administrator>pip3 install packging -i https://pypi.douban.com/simple
Looking in indexes: https://pypi.douban.com/simple
ERROR: Could not find a version that satisfies the requirement packging (from versions: none)
ERROR: No matching distribution found for packging`
若直接搜索，则
`C:\Users\Administrator>pip3 search packging
ERROR: Exception:
Traceback (most recent call last):
  File "d:\program files\python38\lib\site-packages\pip\_internal\cli\base_command.py", line 228, in _main
    status = self.run(options, args)
  File "d:\program files\python38\lib\site-packages\pip\_internal\commands\search.py", line 60, in run
    pypi_hits = self.search(query, options)
  File "d:\program files\python38\lib\site-packages\pip\_internal\commands\search.py", line 80, in search
    hits = pypi.search({'name': query, 'summary': query}, 'or')
  File "d:\program files\python38\lib\xmlrpc\client.py", line 1109, in __call__
    return self.__send(self.__name, args)
  File "d:\program files\python38\lib\xmlrpc\client.py", line 1450, in __request
    response = self.__transport.request(
  File "d:\program files\python38\lib\site-packages\pip\_internal\network\xmlrpc.py", line 45, in request
    return self.parse_response(response.raw)
  File "d:\program files\python38\lib\xmlrpc\client.py", line 1341, in parse_response
    return u.close()
  File "d:\program files\python38\lib\xmlrpc\client.py", line 655, in close
    raise Fault(**self._stack[0])
xmlrpc.client.Fault: <Fault -32500: "RuntimeError: PyPI's XMLRPC API is currently disabled due to unmanageable load and
will be deprecated in the near future. See https://status.python.org/ for more information.">`

**Comment by cosven** [comment]
> 我尝试把包下载下来，硬改setup.py加入#489，然后提示：

这是一个 bug，目前还没有特别好的 workaround。建议可以先在命令行直接运行 `feeluown`。
后续会修复一下这个问题。

**Comment by cosven** [comment]
> > 我尝试把包下载下来，硬改setup.py加入#489，然后提示：
> 
> 这是一个 bug，目前还没有特别好的 workaround。建议可以先在命令行直接运行 `feeluown`。
> 后续会修复一下这个问题。

单独创建了一个 issue 来跟进这个问题：https://github.com/feeluown/FeelUOwn/issues/494。先 close 这个 issue 了。
