### ISSUE TITLE
网易云登录致崩溃

### ISSUE THREAD

**Issue by renyuneyun** [feeluown/FeelUOwn#389]
**Describe the bug**
登录网易云导致程序崩溃。不确定是否和账号本身有关。
从命令行执行feeluown，可得这个报错：
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/fuo_netease/ui.py", line 108, in login
    user = self.create_user(data)
  File "/usr/lib/python3.8/site-packages/fuo_netease/login_controller.py", line 35, in create
    uid = user_data['profile']['userId']
KeyError: 'profile'
zsh: abort (core dumped)  feeluown
```

**To Reproduce**
新安装软件，安装了本地和网易云两个插件。
打开，点选网易云，弹出登录对话框输入用户名和密码，点击登录。
然后程序就崩库了。

**Expected behavior**
登录成功，或提示有错误。

**Desktop:**
 - OS: Archlinux的GNU/Linux
 - Version: 3.5.2

**Additional context**
该账号很久没登录过。刚刚在网页版登录时发现被要求提供手机号。

**Comment by cosven** [comment]
> 刚刚在网页版登录时发现被要求提供手机号。

在网页版登录过一次，之后应该就可以了。

**Comment by cosven** [comment]
https://github.com/feeluown/FeelUOwn/issues/210#issuecomment-304757342
这里有个相似的情况。

之后看看能不能进行一些改进 ~
