### ISSUE TITLE
Brew update fails for v3.6 on macOS big sur

### ISSUE THREAD

**Issue by legendtang** [feeluown/FeelUOwn#421]
**Describe the bug**
Upgrade failure using homebrew.

**To Reproduce**
`brew update`

**Expected behavior**
```

==> Upgrading feeluown/feeluown/feeluown 3.5.3 -> 3.6 --with-battery
==> Downloading https://files.pythonhosted.org/packages/6b/f9/8f3c5bd5571aec4427d65b56ae18b2c783a8911967e895ae21f4f8
Already downloaded: /Users/legend/Library/Caches/Homebrew/downloads/e2c1658160c2027fb317b7cda825b2742e0ecea71005bf90f3e54140573a41f4--feeluown-3.6.tar.gz
==> /usr/local/opt/python@3.8/bin/pip3 install /private/tmp/feeluown-20201116-40239-1211ct1/feeluown-3.6/[macos] --p
Last 15 lines from /Users/legend/Library/Logs/Homebrew/feeluown/01.pip3:
      File "/usr/local/Cellar/python@3.8/3.8.6_1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/local/Cellar/python@3.8/3.8.6_1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/local/Cellar/python@3.8/3.8.6_1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/local/Cellar/python@3.8/3.8.6_1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/local/Cellar/python@3.8/3.8.6_1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/private/tmp/pip-install-a5m8h3zw/pyobjc-core/setup.py", line 601, in run
        % (tuple(map(int, get_sdk_level(self.sdk_root).split("."))))
    ValueError: invalid literal for int() with base 10: ''
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/local/opt/python@3.8/bin/python3.8 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/tmp/pip-install-a5m8h3zw/pyobjc-core/setup.py'"'"'; __file__='"'"'/private/tmp/pip-install-a5m8h3zw/pyobjc-core/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/tmp/pip-record-0y90hrvy/install-record.txt --single-version-externally-managed --prefix /usr/local/Cellar/feeluown/3.6/libexec --compile --install-headers /usr/local/Cellar/feeluown/3.6/libexec/include/python3.8/pyobjc-core Check the logs for full command output.

Do not report this issue to Homebrew/brew or Homebrew/core!


Error: You are using macOS 11.0.
We do not provide support for this released but not yet supported version.
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Discourse, Twitter or any other official channels. You are responsible for
resolving any issues you experience while you are running this
released but not yet supported version.
```

**Desktop:**
 - OS: macOS 11.0
 - Version: feeluown 3.6

**Comment by yejiawei1234** [comment]
I have same issue. But my problem occur in "pip3 install 'feeluown[battery,macos]>=3.0' --upgrade"

**To Reproduce**
Steps to reproduce the behavior:
1. pip3 install 'feeluown[battery,macos]>=3.0' --upgrade

**Desktop:**
 - OS: macOS 11
 - Version: feeluown 3.6

**Additional context**
    ERROR: Command errored out with exit status 1:
     command: /usr/local/opt/python@3.9/bin/python3.9 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/50/v5346r4n67573r8nd1437zwh0000gn/T/pip-install-pzr2rntd/pyobjc-framework-cocoa/setup.py'"'"'; __file__='"'"'/private/var/folders/50/v5346r4n67573r8nd1437zwh0000gn/T/pip-install-pzr2rntd/pyobjc-framework-cocoa/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/50/v5346r4n67573r8nd1437zwh0000gn/T/pip-pip-egg-info-pknh3_dd
         cwd: /private/var/folders/50/v5346r4n67573r8nd1437zwh0000gn/T/pip-install-pzr2rntd/pyobjc-framework-cocoa/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/50/v5346r4n67573r8nd1437zwh0000gn/T/pip-install-pzr2rntd/pyobjc-framework-cocoa/setup.py", line 23, in <module>
        Extension(
      File "/private/var/folders/50/v5346r4n67573r8nd1437zwh0000gn/T/pip-install-pzr2rntd/pyobjc-framework-cocoa/pyobjc_setup.py", line 436, in Extension
        % (tuple(map(int, os.path.basename(data)[6:-4].split("."))))
    ValueError: invalid literal for int() with base 10: ''
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by cosven** [comment]
I have updated feeluown formula https://github.com/feeluown/homebrew-feeluown/commit/7952f1ee3028f445e18e34ddd2b49e58e9bbcdb4 and it works on my macOS.
Can you try to reinstall feeluown with following command
```
brew resinstall feeluown/feeluown/feeluown
```

**Comment by legendtang** [comment]
> I have updated feeluown formula [feeluown/homebrew-feeluown@7952f1e](https://github.com/feeluown/homebrew-feeluown/commit/7952f1ee3028f445e18e34ddd2b49e58e9bbcdb4) and it works on my macOS.
> Can you try to reinstall feeluown with following command
> 
> ```
> brew reinstall feeluown/feeluown/feeluown
> ```

It has the same issues, except that the error occurs on Python v3.9.0
```
brew reinstall feeluown/feeluown/feeluown
Warning: You are using macOS 11.0.
We do not provide support for this released but not yet supported version.
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Twitter or any other official channels. You are responsible for resolving
any issues you experience while you are running this
released but not yet supported version.

==> Downloading https://files.pythonhosted.org/packages/6b/f9/8f3c5bd5571aec4427d65b56ae18b2c783a8911967e895ae21f4f8d
Already downloaded: /Users/legend/Library/Caches/Homebrew/downloads/e2c1658160c2027fb317b7cda825b2742e0ecea71005bf90f3e54140573a41f4--feeluown-3.6.tar.gz
==> Reinstalling feeluown/feeluown/feeluown --with-battery
==> /usr/local/opt/python@3.9/bin/pip3 install /private/tmp/feeluown-20201117-52833-1hk8tun/feeluown-3.6/[macos] --pr
Last 15 lines from /Users/legend/Library/Logs/Homebrew/feeluown/01.pip3:
      File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/private/tmp/pip-install-jptnp820/pyobjc-core/setup.py", line 601, in run
        % (tuple(map(int, get_sdk_level(self.sdk_root).split("."))))
    ValueError: invalid literal for int() with base 10: ''
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/local/opt/python@3.9/bin/python3.9 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/tmp/pip-install-jptnp820/pyobjc-core/setup.py'"'"'; __file__='"'"'/private/tmp/pip-install-jptnp820/pyobjc-core/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/tmp/pip-record-im6li5xy/install-record.txt --single-version-externally-managed --prefix /usr/local/Cellar/feeluown/3.6/libexec --compile --install-headers /usr/local/Cellar/feeluown/3.6/libexec/include/python3.9/pyobjc-core Check the logs for full command output.

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/feeluown/homebrew-feeluown/issues


Error: You are using macOS 11.0.
We do not provide support for this released but not yet supported version.
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Twitter or any other official channels. You are responsible for resolving
any issues you experience while you are running this
released but not yet supported version.
```

**Comment by cosven** [comment]
从报错来看，应该是在 `pip3 install pyobjc-framework-Cocoa` 的时候出错了。
可以看到，它似乎是在执行 `python3 setup.py` 来安装 pyobjc。

但理论上不应该执行这个步骤，因为 `pyobjc-framework-Cocoa` 包提供了 wheel 包，pip 应该会优先选择 wheel 包的。这里我目前也不是很懂为什么会出现这种情况 🤔

**Comment by cosven** [comment]
似乎懂了，仔细去看了下 `pyobjc-framework-Cocoa` 提供的 wheel 包，是 `pyobjc_framework_Cocoa-6.2.2-cp39-cp39-macosx_10_9_x86_64.whl`，怀疑是 pip 认为它不兼容 `11.0`，所以没有安装 wheel 包，转而从源码编译。

**Comment by cosven** [comment]
你可以试试下面这个命令能不能执行成功么？
```sh
pip3 -V
pip3 install https://files.pythonhosted.org/packages/79/6f/eafcba859fbc760032236bb55f8e604a1181d752432eff1cb27e958ce580/pyobjc_framework_Cocoa-6.2.2-cp39-cp39-macosx_10_9_x86_64.whl
```

如果可以的话，可以这样安装
```
pip3 install https://files.pythonhosted.org/packages/79/6f/eafcba859fbc760032236bb55f8e604a1181d752432eff1cb27e958ce580/pyobjc_framework_Cocoa-6.2.2-cp39-cp39-macosx_10_9_x86_64.whl
pip3 install https://files.pythonhosted.org/packages/a9/fa/73951ee3ac898e703879f90bae78d48a55c9af0c5dbef25d154425ad8243/pyobjc_framework_Quartz-6.2.2-cp39-cp39-macosx_10_9_x86_64.whl
pip3 install 'feeluown[battery]>=3.6' --upgrade
```

**Comment by legendtang** [comment]
> 似乎懂了，仔细去看了下 `pyobjc-framework-Cocoa` 提供的 wheel 包，是 `pyobjc_framework_Cocoa-6.2.2-cp39-cp39-macosx_10_9_x86_64.whl`，怀疑是 pip 认为它不兼容 `11.0`，所以没有安装 wheel 包，转而从源码编译。
> 
> 你可以试试下面这个命令能不能执行成功么？
> 
> ```shell
> pip3 -V
> pip3 install https://files.pythonhosted.org/packages/79/6f/eafcba859fbc760032236bb55f8e604a1181d752432eff1cb27e958ce580/pyobjc_framework_Cocoa-6.2.2-cp39-cp39-macosx_10_9_x86_64.whl
> ```
> 
> 如果可以的话，可以这样安装
> 
> ```
> pip3 install https://files.pythonhosted.org/packages/79/6f/eafcba859fbc760032236bb55f8e604a1181d752432eff1cb27e958ce580/pyobjc_framework_Cocoa-6.2.2-cp39-cp39-macosx_10_9_x86_64.whl
> pip3 install https://files.pythonhosted.org/packages/a9/fa/73951ee3ac898e703879f90bae78d48a55c9af0c5dbef25d154425ad8243/pyobjc_framework_Quartz-6.2.2-cp39-cp39-macosx_10_9_x86_64.whl
> pip3 install 'feeluown[battery]>=3.6' --upgrade
> ```

试了下，确实不行：
```
ERROR: pyobjc_framework_Cocoa-6.2.2-cp39-cp39-macosx_10_9_x86_64.whl is not a supported wheel on this platform.
```

**Comment by cosven** [comment]
`pyobjc_framework_Cocoa` 本来是用来实现全局热键的。既然这个包目前在 macos 11 上不能安装，可以暂时不安装这个包，不影响主体功能。

可以直接这样安装
```
pip3 install 'feeluown[battery]>=3.6' --upgrade
```
然后运行
```
fuo -v
```

**Comment by cosven** [comment]
有童鞋在 11.1 上安装成功了... 神奇..
https://dpaste.com/7Y38XRPFR

**Comment by cosven** [comment]
根据我对多位童鞋的观察，当前是可以在 macOS big sur 安装成功的。

**Comment by cosven** [comment]
先 close 了 ~
