### ISSUE TITLE
FeelUOwn启动后无法自动读取上一次退出时听的歌

### ISSUE THREAD

**Issue by orzogc** [feeluown/FeelUOwn#454]
**Describe the bug**
FeelUOwn启动后无法自动读取上一次退出时听的歌

**To Reproduce**
1. 启动FeelUOwn
2. 登陆网易云音乐帐号
3. 随便播放一个歌单
4. 退出FeelUOwn
5. 再启动FeelUOwn

**Expected behavior**
FeelUOwn启动后能自动读取上一次退出时听的歌，FeelUOwn 3.6.1 和netease插件 0.4.4 是可以的

**Desktop:**
 - OS: Arch Linux
 - Version: FeelUOwn 3.7.0 和 3.7.1，netease插件 0.5

**Additional context**
`stdout.log`中间的大量重复输出就不贴了
```
[2021-01-27 11:36:17,748 fuo_local:34] [INFO]: Register provider: <fuo_local.provider.LocalProvider object at 0x7fc44a8c5a00>
[2021-01-27 11:36:17,751 fuo_local.provider:238] [INFO]: 共扫描到 0 个音乐文件，准备将其录入本地音乐库
[2021-01-27 11:36:17,752 fuo_local.provider:242] [INFO]: 录入本地音乐库完毕
[2021-01-27 11:36:18,834 feeluown.utils.reader:215] [INFO]: trigger read_func(0, 182)
[2021-01-27 11:36:18,836 feeluown.rpc.server:48] [INFO]: Fuo daemon run at 127.0.0.1:23333
[2021-01-27 11:36:18,904 feeluown.player.player:141] [ERROR]: prepare media failed
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/feeluown/media.py", line 111, in _get_index
    q_idx = l.index(q)
ValueError: 'hq' is not in list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/feeluown/player/player.py", line 137, in a_set_current_song
    media = await future
  File "/usr/lib/python3.9/site-packages/qasync/__init__.py", line 139, in run
    r = callback(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/feeluown/player/player.py", line 205, in prepare_media
    return self._app.library.song_prepare_media(song, self.audio_select_policy)
  File "/usr/lib/python3.9/site-packages/feeluown/library/library.py", line 321, in song_prepare_media
    media, _ = provider.song_select_media(song, policy)
  File "/usr/lib/python3.9/site-packages/feeluown/library/provider_v2.py", line 46, in song_select_media
    sorted_q_list = Quality.SortPolicy.apply(
  File "/usr/lib/python3.9/site-packages/feeluown/media.py", line 61, in apply
    q_idx = cls._get_index(q, l)
  File "/usr/lib/python3.9/site-packages/feeluown/media.py", line 113, in _get_index
    raise ValueError('invalid policy string: quality not found')
ValueError: invalid policy string: quality not found
[2021-01-27 11:36:18,906 feeluown.task:39] [INFO]: preemptive-task(set-current-song): try to cancel previous
[2021-01-27 11:36:18,907 feeluown.player.player:114] [ERROR]: async set current song failed
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/feeluown/player/player.py", line 112, in cb
    future.result()
asyncio.exceptions.CancelledError
[2021-01-27 11:36:18,998 feeluown.player.player:141] [ERROR]: prepare media failed
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/feeluown/media.py", line 111, in _get_index
    q_idx = l.index(q)
ValueError: 'hq' is not in list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/feeluown/player/player.py", line 137, in a_set_current_song
    media = await future
  File "/usr/lib/python3.9/site-packages/qasync/__init__.py", line 139, in run
    r = callback(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/feeluown/player/player.py", line 205, in prepare_media
    return self._app.library.song_prepare_media(song, self.audio_select_policy)
  File "/usr/lib/python3.9/site-packages/feeluown/library/library.py", line 321, in song_prepare_media
    media, _ = provider.song_select_media(song, policy)
  File "/usr/lib/python3.9/site-packages/feeluown/library/provider_v2.py", line 46, in song_select_media
    sorted_q_list = Quality.SortPolicy.apply(
  File "/usr/lib/python3.9/site-packages/feeluown/media.py", line 61, in apply
    q_idx = cls._get_index(q, l)
  File "/usr/lib/python3.9/site-packages/feeluown/media.py", line 113, in _get_index
    raise ValueError('invalid policy string: quality not found')
ValueError: invalid policy string: quality not found
[2021-01-27 11:36:19,001 feeluown.task:39] [INFO]: preemptive-task(set-current-song): try to cancel previous
[2021-01-27 11:36:19,001 feeluown.player.player:114] [ERROR]: async set current song failed
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/feeluown/player/player.py", line 112, in cb
    future.result()
asyncio.exceptions.CancelledError
[2021-01-27 11:36:19,002 feeluown.player.player:141] [ERROR]: prepare media failed
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/feeluown/media.py", line 111, in _get_index
    q_idx = l.index(q)
ValueError: 'hq' is not in list
```

**Comment by orzogc** [comment]
版本 3.7.2 解决了这个bug，谢谢

**Comment by cosven** [comment]
好 ~

昨天没来得及看 issue，不好意思 =。=
