### ISSUE TITLE
Windows 生成桌面图标失败

### ISSUE THREAD

**Issue by cosven** [feeluown/FeelUOwn#494]
**Describe the bug**
运行 `python -m feeluown genicon` 报错。

https://github.com/feeluown/FeelUOwn/issues/314#issuecomment-862006603

**To Reproduce**
```
C:\Users\Administrator>python -m feeluown genicon
Generate icon, then you can see app on desktop. 
No conda env active, defaulting to base 
Traceback (most recent call last): 
File "D:\Program Files\Python38\lib\runpy.py", line 194, in _run_module_as_main return _run_code(code, main_globals, None, 
File "D:\Program Files\Python38\lib\runpy.py", line 87, in _run_code exec(code, run_globals) 
File "d:\download\feeluown\feeluown\__main__.py", line 13, in <module> run() 
File "d:\download\feeluown\feeluown\entry_points\run.py", line 31, in run return run_cli(args) 
File "d:\download\feeluown\feeluown\entry_points\run_cli.py", line 5, in run_cli climain(args) 
File "d:\download\feeluown\feeluown\cli\cli.py", line 289, in climain generate_icon() 
File "d:\download\feeluown\feeluown\cli\install.py", line 123, in generate_icon gen_for_win32() 
File "d:\download\feeluown\feeluown\cli\install.py", line 115, in gen_for_win32 make_shortcut(command, name=name, icon=ico, terminal=False) 
File "D:\Program Files\Python38\lib\site-packages\pyshortcuts\windows.py", line 105, in make_shortcut scut = shortcut(script, userfolders, name=name, description=description, 
File "D:\Program Files\Python38\lib\site-packages\pyshortcuts\shortcut.py", line 81, in shortcut if icon is not None and len(icon) > 0: TypeError: object of type 'WindowsPath' has no len()
```

**Comment by cosven** [comment]
错误原因是：genicon 使用的路径是 pathlib 的 WindowsPath 对象，而不是普通的 string，它没有实现 `len` 协议。而 pyshortcuts 这里使用 `len(icon)` 来判断路径是否为空。

```
pyshortcuts\shortcut.py", line 81, in shortcut if icon is not None and len(icon) > 0: TypeError: object of type 'WindowsPath' has no len()
```

建议的修复方式：将 `ico` 转成 string 传入

https://github.com/feeluown/FeelUOwn/blob/9cbd5f59a2d8e1083681677bd16eeab234b178d9/feeluown/cli/install.py#L113-L115
