### ISSUE TITLE
网易云音乐云盘歌曲播放出错

### ISSUE THREAD

**Issue by maz-1** [feeluown/FeelUOwn#499]
**Describe the bug**
云盘歌曲播放出错
终端日志：

```

[2021-08-16 13:59:46,713 feeluown.task:83] [WARNING]: Task prepare-media failed: 'NoneType' object is not subscriptable
[2021-08-16 13:59:46,714 feeluown.player.playlist:414] [ERROR]: prepare media failed due to unknown error, so we mark the song as a bad one
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/feeluown/player/playlist.py", line 379, in a_set_current_song
    media = await self._prepare_media(song)
  File "/usr/lib/python3.9/site-packages/feeluown/player/playlist.py", line 451, in _prepare_media
    return await task_spec.bind_blocking_io(
  File "/usr/lib/python3.9/site-packages/feeluown/task.py", line 81, in _cb
    future.result()
  File "/usr/lib/python3.9/site-packages/qasync/__init__.py", line 142, in run
    r = callback(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/feeluown/library/library.py", line 438, in song_prepare_media
    media, _ = provider.song_select_media(song, policy)
  File "/usr/lib/python3.9/site-packages/feeluown/library/provider_v2.py", line 65, in song_select_media
    available_q_set = set(self.song_list_quality(song))
  File "/usr/lib/python3.9/site-packages/fuo_netease/provider.py", line 67, in song_list_quality
    return list(self._song_get_q_media_mapping(song))
  File "/usr/lib/python3.9/site-packages/fuo_netease/provider.py", line 180, in _song_get_q_media_mapping
    if (song_data[key]['br'] - highest_bitrate) > 10000:
TypeError: 'NoneType' object is not subscriptable

```

**To Reproduce**
使用网易云音乐云盘上传歌曲
在feeluown中播放

**Expected behavior**
正常播放

**Screenshots**

**Desktop:**
 - OS: ArchLinux
 - Version: feeluown 3.7.10

**Additional context**

**Comment by maz-1** [comment]
看提示似乎是获取云盘音乐属性的时候缺了bitrate信息？

**Comment by maz-1** [comment]
我看了一下/usr/lib/python3.9/site-packages/fuo_netease/provider.py这个文件，然后179行下面加了`print(song_data)`，然后播放云盘音乐打印的内容：
```

{'name': None, 'id': 1844514484, 'pst': 0, 't': 1, 'ar': [{'id': 0, 'name': None, 'tns': [], 'alias': []}], 'alia': [], 'pop': 0.0, 'st': 0, 'rt': None, 'fee': 0, 'v': 2, 'crbt': None, 'cf': None, 'al': {'id': 0, 'name': None, 'picUrl': 'http://p3.music.126.net/UeTuwE7pvjBpypWLudqukA==/3132508627578625.jpg', 'tns': [], 'pic': 0}, 'dt': 189405, 'h': None, 'm': None, 'l': {'br': 128000, 'fid': 0, 'size': 3031502, 'vd': -41.0}, 'a': None, 'cd': None, 'no': 0, 'rtUrl': None, 'ftype': 0, 'rtUrls': [], 'djId': 0, 'copyright': 0, 's_id': 0, 'mark': 0, 'originCoverType': 0, 'originSongSimpleData': None, 'resourceState': True, 'version': 2, 'single': 0, 'noCopyrightRcmd': None, 'rtype': 0, 'rurl': None, 'mst': 9, 'cp': 0, 'mv': 0, 'publishTime': 0}


```

看提示应该是我上传的音乐bitrate比较低，然后'h'和'm'这两个dict是NoneType导致出错，所以我又改了原来的180行：

```

if song_data[key] is None or (song_data[key]['br'] - highest_bitrate) > 10000:

```

然后又有新的错误

```

[2021-08-16 14:21:33,587 feeluown.task:83] [WARNING]: Task prepare-media failed: 
[2021-08-16 14:21:35,866 qasync._QEventLoop:722] [ERROR]: Exception in callback PreemptiveTaskSpec._cb(<Task cancell...ylist.py:375>>)
handle: <Handle PreemptiveTaskSpec._cb(<Task cancell...ylist.py:375>>)>
Traceback (most recent call last):
  File "/usr/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/lib/python3.9/site-packages/feeluown/task.py", line 81, in _cb
    future.result()
asyncio.exceptions.CancelledError
[2021-08-16 14:21:36,078 feeluown.task:83] [WARNING]: Task mpris2-update-property failed: {'name': ['Field may not be null.'], 'album': {'name': ['Field may not be null.']}}
[2021-08-16 14:21:36,078 feeluown.linux.mpris2:119] [ERROR]: mpris update song props failed
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/feeluown/linux/mpris2.py", line 117, in cb
    future.result()
  File "/usr/lib/python3.9/site-packages/feeluown/task.py", line 81, in _cb
    future.result()
  File "/usr/lib/python3.9/site-packages/qasync/__init__.py", line 142, in run
    r = callback(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/feeluown/linux/mpris2.py", line 127, in _update_song_props
    song = self._app.library.song_upgrade(song)
  File "/usr/lib/python3.9/site-packages/feeluown/library/library.py", line 412, in song_upgrade
    upgraded_song = provider.song_get(song.identifier)
  File "/usr/lib/python3.9/site-packages/fuo_netease/provider.py", line 60, in song_get
    return _deserialize(data, V2SongSchema)
  File "/usr/lib/python3.9/site-packages/fuo_netease/models.py", line 29, in _deserialize
    obj = schema.load(data)
  File "/usr/lib/python3.9/site-packages/marshmallow/schema.py", line 719, in load
    return self._do_load(
  File "/usr/lib/python3.9/site-packages/marshmallow/schema.py", line 901, in _do_load
    raise exc
marshmallow.exceptions.ValidationError: {'name': ['Field may not be null.'], 'album': {'name': ['Field may not be null.']}}
[2021-08-16 14:21:36,098 feeluown.task:83] [WARNING]: Task update-mv-btn-status failed: {'name': ['Field may not be null.']}


```

**Comment by cosven** [comment]
非常感谢你的反馈以及耐心的尝试。下面这个修复方式是正确的。
> `if song_data[key] is None or (song_data[key]['br'] - highest_bitrate) > 10000:`

----

后面这个 ValidationError 是因为这首歌的名字为空。之前还没遇到过这种情况，所以程序没有考虑到这种 corner case。我去修复一下。

**Comment by maz-1** [comment]
> 非常感谢你的反馈以及耐心的尝试。下面这个修复方式是正确的。
> 
> > `if song_data[key] is None or (song_data[key]['br'] - highest_bitrate) > 10000:`
> 
> 后面这个 ValidationError 是因为这首歌的名字为空。之前还没遇到过这种情况，所以程序没有考虑到这种 corner case。我去修复一下。

是的，有几首音乐是从视频提取的，没加tag，如果加了tag应该不会出错
