### ISSUE TITLE
Manjaro下启动失败：“io.UnsupportedOperation: not readable”

### ISSUE THREAD

**Issue by Karmenzind** [feeluown/FeelUOwn#517]
**Describe the bug**
启动失败

**To Reproduce**
目前执行`feeluown -d -v`的结果

普通用户：
```
feeluown -d -v
[2021-12-03 16:06:53,343 asyncio:59] [DEBUG]: Using selector: _Selector
[2021-12-03 16:06:53,357 feeluown.player.mpvplayer:88] [DEBUG]: Player initialize finished.
[2021-12-03 16:06:53,357 feeluown.player.mpvplayer:176] [DEBUG]: Player receive duration changed signal
/usr/lib/python3.9/site-packages/fuzzywuzzy/fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')
[2021-12-03 16:06:53,601 fuo_local:34] [INFO]: Register provider: <fuo_local.provider.LocalProvider object at 0x7f0514718580>
[2021-12-03 16:06:53,601 qasync._QEventLoop:23] [DEBUG]: Running callback <bound method LocalProvider.scan of <fuo_local.provider.LocalProvider object at 0x7f0514718580>> with args () in executor
[2021-12-03 16:06:53,601 qasync._QEventLoop:34] [DEBUG]: Using default executor
[2021-12-03 16:06:53,601 qasync._QEventLoop:38] [DEBUG]: Creating default executor
[2021-12-03 16:06:53,601 qasync.QThreadExecutor:205] [DEBUG]: Submitting callback <bound method LocalProvider.scan of <fuo_local.provider.LocalProvider object at 0x7f0514718580>> with args () and kwargs {} to thread worker queue
[2021-12-03 16:06:53,602 qasync._QThreadWorker:139] [DEBUG]: #1 got callback <bound method LocalProvider.scan of <fuo_local.provider.LocalProvider object at 0x7f0514718580>> with args () and kwargs {} from queue
[2021-12-03 16:06:53,602 qasync._QThreadWorker:147] [DEBUG]: Invoking callback
[2021-12-03 16:06:53,602 fuo_local.provider:236] [DEBUG]: 正在扫描目录(/home/x/Music)...
[2021-12-03 16:06:53,602 fuo_local.provider:238] [INFO]: 共扫描到 0 个音乐文件，准备将其录入本地音乐库
[2021-12-03 16:06:53,602 fuo_local.provider:242] [INFO]: 录入本地音乐库完毕
[2021-12-03 16:06:53,602 feeluown.utils.utils:42] [DEBUG]: function scan executed time: 0.414090 ms
[2021-12-03 16:06:53,602 qasync._QThreadWorker:154] [DEBUG]: Setting Future result: None
[2021-12-03 16:06:53,624 feeluown.collection:228] [INFO]: Generating collection library
Traceback (most recent call last):
  File "/usr/bin/feeluown", line 33, in <module>
    sys.exit(load_entry_point('feeluown==3.7.11', 'console_scripts', 'feeluown')())
  File "/usr/lib/python3.9/site-packages/feeluown/entry_points/run.py", line 56, in run
    return run_forever(args, config)
  File "/usr/lib/python3.9/site-packages/feeluown/entry_points/run_app.py", line 46, in run_forever
    init_app(app)
  File "/usr/lib/python3.9/site-packages/feeluown/app.py", line 331, in init_app
    app.coll_uimgr.initialize()
  File "/usr/lib/python3.9/site-packages/feeluown/uimodels/collection.py", line 42, in initialize
    self._scan()
  File "/usr/lib/python3.9/site-packages/feeluown/uimodels/collection.py", line 52, in _scan
    for coll in self._app.coll_mgr.scan():
  File "/usr/lib/python3.9/site-packages/feeluown/collection.py", line 211, in scan
    fpath = self.generate_library_coll_if_needed(default_fpaths)
  File "/usr/lib/python3.9/site-packages/feeluown/collection.py", line 235, in generate_library_coll_if_needed
    for line in f:
io.UnsupportedOperation: not readable
```

root：（此前有报错缺少cuda的so文件，已经通过安装nvidia-utils解决）
```
feeluown -d -v
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
[2021-12-03 16:14:44,941 asyncio:59] [DEBUG]: Using selector: _Selector
[2021-12-03 16:14:44,956 feeluown.player.mpvplayer:176] [DEBUG]: Player receive duration changed signal
[2021-12-03 16:14:44,956 feeluown.player.mpvplayer:88] [DEBUG]: Player initialize finished.
/usr/lib/python3.9/site-packages/fuzzywuzzy/fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')
[2021-12-03 16:14:45,196 fuo_local:34] [INFO]: Register provider: <fuo_local.provider.LocalProvider object at 0x7f59fd643160>
[2021-12-03 16:14:45,196 qasync._QEventLoop:23] [DEBUG]: Running callback <bound method LocalProvider.scan of <fuo_local.provider.LocalProvider object at 0x7f59fd643160>> with args () in executor
[2021-12-03 16:14:45,196 qasync._QEventLoop:34] [DEBUG]: Using default executor
[2021-12-03 16:14:45,196 qasync._QEventLoop:38] [DEBUG]: Creating default executor
[2021-12-03 16:14:45,197 qasync.QThreadExecutor:205] [DEBUG]: Submitting callback <bound method LocalProvider.scan of <fuo_local.provider.LocalProvider object at 0x7f59fd643160>> with args () and kwargs {} to thread worker queue
[2021-12-03 16:14:45,197 qasync._QThreadWorker:139] [DEBUG]: #9 got callback <bound method LocalProvider.scan of <fuo_local.provider.LocalProvider object at 0x7f59fd643160>> with args () and kwargs {} from queue
[2021-12-03 16:14:45,197 qasync._QThreadWorker:147] [DEBUG]: Invoking callback
[2021-12-03 16:14:45,197 fuo_local.provider:236] [DEBUG]: 正在扫描目录(/root/Music)...
[2021-12-03 16:14:45,197 fuo_local.provider:238] [INFO]: 共扫描到 0 个音乐文件，准备将其录入本地音乐库
[2021-12-03 16:14:45,197 fuo_local.provider:242] [INFO]: 录入本地音乐库完毕
[2021-12-03 16:14:45,197 feeluown.utils.utils:42] [DEBUG]: function scan executed time: 0.197688 ms
[2021-12-03 16:14:45,198 qasync._QThreadWorker:154] [DEBUG]: Setting Future result: None
Traceback (most recent call last):
  File "/usr/bin/feeluown", line 33, in <module>
    sys.exit(load_entry_point('feeluown==3.7.11', 'console_scripts', 'feeluown')())
  File "/usr/lib/python3.9/site-packages/feeluown/entry_points/run.py", line 56, in run
    return run_forever(args, config)
  File "/usr/lib/python3.9/site-packages/feeluown/entry_points/run_app.py", line 50, in run_forever
    run_app(app)
  File "/usr/lib/python3.9/site-packages/feeluown/app.py", line 353, in run_app
    run_mpris2_server(app)
  File "/usr/lib/python3.9/site-packages/feeluown/linux/__init__.py", line 25, in run_mpris2_server
    session_bus = dbus.SessionBus()
  File "/usr/lib/python3.9/site-packages/dbus/_dbus.py", line 212, in __new__
    return Bus.__new__(cls, Bus.TYPE_SESSION, private=private,
  File "/usr/lib/python3.9/site-packages/dbus/_dbus.py", line 102, in __new__
    bus = BusConnection.__new__(subclass, bus_type, mainloop=mainloop)
  File "/usr/lib/python3.9/site-packages/dbus/bus.py", line 124, in __new__
    bus = cls._new_for_bus(address_or_type, mainloop=mainloop)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NotSupported: Using X11 for dbus-daemon autolaunch was disabled at compile time, set your DBUS_SESSION_BUS_ADDRESS instead
[1]    1266273 segmentation fault (core dumped)  feeluown -d -v
```

**Expected behavior**

**Screenshots**

**Desktop:**

 - OS: `Linux version 5.4.159-1-MANJARO (builduser@fv-az83-94) (gcc version 11.1.0 (GCC)) #1 SMP PREEMPT Fri Nov 12 20:25:49 UTC 2021`
 - Version: 
 ```
community/feeluown 3.7.11-1 (feeluown-full) [installed]
community/feeluown-local 0.2.1-2 (feeluown-full) [installed]
community/feeluown-netease 0.7.1-1 (feeluown-full) [installed]
community/feeluown-qqmusic 0.3.3-1 (feeluown-full) [installed]
```

**Additional context**

**Comment by cosven** [comment]
这个问题和系统环境比较相关，感觉主要是 DBUS 的问题，还得查一查。

cuda 的文件缺了没关系，不过确实每次都会在标准输出中打印一下。有点烦人。

**Comment by BruceZhang1993** [comment]
@Karmenzind  
root 用户启动失败是正常的，正常情况下 root 用户没有 dbus session，所以 mpris 服务无法启动的
主要问题还是第一个

**Comment by cosven** [comment]
第一个问题，已经 fix 了，之后有时间加个单测。
https://github.com/feeluown/FeelUOwn/commit/864fb93a498cdee062697a3b5626b76d15a88bea

**Comment by Karmenzind** [comment]
谢谢。

**Comment by cosven** [comment]
@Karmenzind master 分支的代码在你的环境可以正常运行么？

这个 issue 的第二个问题，我单独建了 issue，我先把这个 issue close 了 ~

**Comment by Karmenzind** [comment]
好，感谢
