### ISSUE TITLE
通过 root 用户启动时，mpris 功能会报错

### ISSUE THREAD

**Issue by cosven** [feeluown/FeelUOwn#521]
**Describe the bug**
root 用户使用时，mpris 功能会报错

```
[2021-12-03 16:14:45,198 qasync._QThreadWorker:154] [DEBUG]: Setting Future result: None
Traceback (most recent call last):
  File "/usr/bin/feeluown", line 33, in <module>
    sys.exit(load_entry_point('feeluown==3.7.11', 'console_scripts', 'feeluown')())
  File "/usr/lib/python3.9/site-packages/feeluown/entry_points/run.py", line 56, in run
    return run_forever(args, config)
  File "/usr/lib/python3.9/site-packages/feeluown/entry_points/run_app.py", line 50, in run_forever
    run_app(app)
  File "/usr/lib/python3.9/site-packages/feeluown/app.py", line 353, in run_app
    run_mpris2_server(app)
  File "/usr/lib/python3.9/site-packages/feeluown/linux/__init__.py", line 25, in run_mpris2_server
    session_bus = dbus.SessionBus()
  File "/usr/lib/python3.9/site-packages/dbus/_dbus.py", line 212, in __new__
    return Bus.__new__(cls, Bus.TYPE_SESSION, private=private,
  File "/usr/lib/python3.9/site-packages/dbus/_dbus.py", line 102, in __new__
    bus = BusConnection.__new__(subclass, bus_type, mainloop=mainloop)
  File "/usr/lib/python3.9/site-packages/dbus/bus.py", line 124, in __new__
    bus = cls._new_for_bus(address_or_type, mainloop=mainloop)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NotSupported: Using X11 for dbus-daemon autolaunch was disabled at compile time, set your DBUS_SESSION_BUS_ADDRESS instead
[1]    1266273 segmentation fault (core dumped)  feeluown -d -v
```

**To Reproduce**
使用 root 用户启动。详情请参考 https://github.com/feeluown/FeelUOwn/issues/517

**Expected behavior**
程序不报错，更不应该 crash

**Comment by cosven** [comment]
根据日志看，这个 segfault 和 dbus 报错并没有关联，所以这个 bug 的严重程度暂定为 minor ~ cc @Karmenzind
