### ISSUE TITLE
TypeError in progress_slider.py

### ISSUE THREAD

**Issue by oldherl** [feeluown/FeelUOwn#523]
**Describe the bug**
`TypeError: setValue(self, int): argument 1 has unexpected type 'float'`

**To Reproduce**
1. run feeluown in a terminal
2. See endless error outputs like this:
```
[2021-12-19 12:47:52,319 feeluown.utils.dispatch:64] [ERROR]: run update_state with (22.837488990929927,) failed
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/feeluown/utils/dispatch.py", line 62, in worker
    func(*args)
  File "/usr/lib/python3.10/site-packages/feeluown/gui/widgets/progress_slider.py", line 42, in update_state
    self.setValue(s)
TypeError: setValue(self, int): argument 1 has unexpected type 'float'
[2021-12-19 12:47:52,320 feeluown.utils.dispatch:64] [ERROR]: run update_state with (22.837488990929927,) failed
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/feeluown/utils/dispatch.py", line 62, in worker
    func(*args)
  File "/usr/lib/python3.10/site-packages/feeluown/gui/widgets/progress_slider.py", line 42, in update_state
    self.setValue(s)
TypeError: setValue(self, int): argument 1 has unexpected type 'float'
```

**Expected behavior**
no such error should be printed

**Screenshots**

**Desktop:**
 - OS: Arch Linux
 - Version: feeluown 3.7.11-3, python 3.10.1-1, python-pyqt5 5.15.6-6

**Additional context**

**Comment by oldherl** [comment]
Just found it is fixed in 0b0763434ab13fff0a1548e022e46659095ce5b5
