### ISSUE TITLE
不兼容 janus 1.0 版本

### ISSUE THREAD

**Issue by cosven** [feeluown/FeelUOwn#524]
在 janus 1.0 版本中，janus.Queue 在初始化的时候会调用 `asyncio.get_running_loop()`。但当前，FeelUOwn 在初始化 Queue 的时候，loop 实际上还没有运行起来。
```
Traceback (most recent call last):
  File "/home/cosven/coding/FeelUOwn/.venv/bin/fuo", line 33, in <module>
    sys.exit(load_entry_point('feeluown', 'console_scripts', 'fuo')())
  File "/home/cosven/coding/FeelUOwn/feeluown/entry_points/run.py", line 51, in run
    return run_forever(args, config)
  File "/home/cosven/coding/FeelUOwn/feeluown/entry_points/run_app.py", line 37, in run_forever
    app = create_app(config)
  File "/home/cosven/coding/FeelUOwn/feeluown/app.py", line 318, in create_app
    Signal.setup_aio_support()
  File "/home/cosven/coding/FeelUOwn/feeluown/utils/dispatch.py", line 43, in setup_aio_support
    cls.aioqueue = janus.Queue()
  File "/home/cosven/coding/FeelUOwn/.venv/lib/python3.10/site-packages/janus/__init__.py", line 115, in __init__
    self._loop = asyncio.get_running_loop()
RuntimeError: no running event loop
```

**Comment by cosven** [comment]
fixde by c80b5386ccdcfcf0b24dfc253f8d337b1746ef16
