### ISSUE TITLE
网易云插件“发现音乐”模块卡死

### ISSUE THREAD

**Issue by zetako** [feeluown/FeelUOwn#540]
**Describe the bug**
网易云插件“发现音乐”，“私人FM”模块点击之后界面卡死，其他模块能正常使用

**To Reproduce**
1. 点击对应模块模块

**Expected behavior**
正常的打开界面

**Screenshots**
点击发现音乐之后卡死
![Screenshot_20220117_134752](https://user-images.githubusercontent.com/54136740/149714688-398a23fd-45db-4eeb-b1d0-8e7e8d0a6351.png)

**Desktop:**
- OS: Manjaro 21.2.1 Qonos
- Kernel: x86_64 Linux 5.14.21-2-MANJARO
- DE: KDE 5.89.0 / Plasma 5.23.4
- WM: KWin
- FeelUOwn Version: community/feeluown 3.7.12-1（manjaro 官方仓库的包）
- Plugin Version: community/feeluown-netease 0.8-1（manjaro 官方仓库的包）

**Additional context**
- manjaro官方仓库的包应该是从Arch的对应仓库中获取的，看了下上游的版本号，应该是一致的，没有版本落后问题。
- 尝试了在终端打开feeluown，访问发现音乐模块，看是否有错误输出，得到的结果如下（最后那个Kill是我主动Ctrl-C，此时已经卡死了）：
```
# ~ [13:29:55]
➜ feeluown   
/usr/lib/python3.10/site-packages/mpv.py:860: DeprecationWarning: setDaemon() is deprecated, set the daemon attribute instead
  self._event_thread.setDaemon(True)
Icon theme "Numix-Circle" not found.
/usr/lib/python3.10/site-packages/feeluown/plugin.py:145: DeprecationWarning: SelectableGroups dict interface is deprecated. Use select.
  entry_points = importlib.metadata.entry_points().get('fuo.plugins_v1', [])
/usr/lib/python3.10/site-packages/marshmallow/__init__.py:14: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
  from distutils.version import LooseVersion
/usr/lib/python3.10/site-packages/marshmallow/fields.py:181: RemovedInMarshmallow4Warning: The 'missing' argument to fields is deprecated. Use 'load_default' instead.
  warnings.warn(
/usr/lib/python3.10/site-packages/fuzzywuzzy/fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')
/usr/lib/python3.10/site-packages/fuo_local/provider.py:18: DeprecationWarning: use feeluown.library please
  from fuocore.provider import AbstractProvider
/usr/lib/python3.10/site-packages/fuo_local/provider.py:19: DeprecationWarning: use feeluown.utils.utils please
  from fuocore.utils import elfhash
/usr/lib/python3.10/site-packages/fuo_local/provider.py:21: DeprecationWarning: use feeluown.media please
  from fuocore.media import Media, MediaType
/usr/lib/python3.10/site-packages/fuo_local/provider.py:22: DeprecationWarning: use feeluown.models please
  from fuocore.models import AlbumType
/usr/lib/python3.10/site-packages/fuo_local/models.py:10: DeprecationWarning: use feeluown.utils.reader please
  from fuocore.reader import RandomSequentialReader
/usr/lib/python3.10/site-packages/fuo_qqmusic/excs.py:1: DeprecationWarning: use feeluown.excs please
  from fuocore.excs import ProviderIOError
/usr/lib/python3.10/site-packages/fuo_qqmusic/ui.py:6: DeprecationWarning: use feeluown.utils.aio please
  from fuocore import aio
Cannot load libcuda.so.1
[2022-01-17 13:30:01,106 qasync._QEventLoop:736] [ERROR]: Task exception was never retrieved
future: <Task finished name='Task-5' coro=<start_server() done, defined at /usr/lib/python3.10/asyncio/streams.py:53> exception=TypeError("BaseEventLoop.create_server() got an unexpected keyword argument 'loop'")>
Traceback (most recent call last):
  File "/usr/lib/python3.10/asyncio/streams.py", line 84, in start_server
    return await loop.create_server(factory, host, port, **kwds)
TypeError: BaseEventLoop.create_server() got an unexpected keyword argument 'loop'
[2022-01-17 13:30:01,530 feeluown.utils.dispatch:64] [ERROR]: run update_state with (229.43446319269108,) failed
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/feeluown/utils/dispatch.py", line 62, in worker
    func(*args)
  File "/usr/lib/python3.10/site-packages/feeluown/gui/widgets/progress_slider.py", line 42, in update_state
    self.setValue(s)
TypeError: setValue(self, int): argument 1 has unexpected type 'float'
[2022-01-17 13:30:01,532 feeluown.utils.dispatch:64] [ERROR]: run update_state with (229.43446319269108,) failed
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/feeluown/utils/dispatch.py", line 62, in worker
    func(*args)
  File "/usr/lib/python3.10/site-packages/feeluown/gui/widgets/progress_slider.py", line 42, in update_state
    self.setValue(s)
TypeError: setValue(self, int): argument 1 has unexpected type 'float'
[2022-01-17 13:30:01,533 feeluown.utils.dispatch:64] [ERROR]: run set_duration with (232.306939,) failed
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/feeluown/utils/dispatch.py", line 62, in worker
    func(*args)
  File "/usr/lib/python3.10/site-packages/feeluown/gui/widgets/progress_slider.py", line 36, in set_duration
    self.setRange(0, s)
TypeError: setRange(self, int, int): argument 2 has unexpected type 'float'
[2022-01-17 13:30:01,534 feeluown.utils.dispatch:64] [ERROR]: run set_duration with (232.306939,) failed
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/feeluown/utils/dispatch.py", line 62, in worker
    func(*args)
  File "/usr/lib/python3.10/site-packages/feeluown/gui/widgets/progress_slider.py", line 36, in set_duration
    self.setRange(0, s)
TypeError: setRange(self, int, int): argument 2 has unexpected type 'float'
[2022-01-17 13:30:02,420 feeluown.utils.dispatch:64] [ERROR]: run update_state with (229.43444416099763,) failed
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/feeluown/utils/dispatch.py", line 62, in worker
    func(*args)
  File "/usr/lib/python3.10/site-packages/feeluown/gui/widgets/progress_slider.py", line 42, in update_state
    self.setValue(s)
TypeError: setValue(self, int): argument 1 has unexpected type 'float'
[2022-01-17 13:30:02,420 feeluown.utils.dispatch:64] [ERROR]: run update_state with (229.43444416099763,) failed
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/feeluown/utils/dispatch.py", line 62, in worker
    func(*args)
  File "/usr/lib/python3.10/site-packages/feeluown/gui/widgets/progress_slider.py", line 42, in update_state
    self.setValue(s)
TypeError: setValue(self, int): argument 1 has unexpected type 'float'
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/feeluown/gui/widgets/imglist.py", line 187, in paint
    elided_name = fm.elidedText(name, Qt.ElideRight, text_rect.width())
TypeError: elidedText(self, str, Qt.TextElideMode, int, flags: int = 0): argument 3 has unexpected type 'float'
[1]    41882 killed     feeluown
```

**Comment by BruceZhang1993** [comment]
都是和 Python 3.10 兼容有关的问题，FeelUOwn 3.8 版本已经修复了，需要等待 Arch 这边版本跟上来 @zetako

**Comment by zetako** [comment]
> 都是和 Python 3.10 兼容有关的问题，FeelUOwn 3.8 版本已经修复了，需要等待 Arch 这边版本跟上来 @zetako

好的，谢谢。我这边尝试切换到git版本的包，确实已经解决了；arch仓库中有标注out-of-date，之前看的时候没有注意，应该很快能跟进了
