### ISSUE TITLE
name: Bug report

### ISSUE THREAD

**Issue by mgcyung** [feeluown/FeelUOwn#612]
about: Create a report to help us improve
title: ValueError: field MetadataFields.artwork expect <class 'str'>, acture <class 'feeluown.media.Media'>
labels: ''
assignees: ''

**Describe the bug**
For loaded local musics, some of them can not be played.

**To Reproduce**
1. Run 'feeluown -d'
2. Click on '本地音乐'
3. Double click some 'music'
4. See the error
`
[2022-08-07 19:32:58,064 qasync._QEventLoop:23] [DEBUG]: Running callback <bound method Library.song_prepare_media of <feeluown.library.library.Library object at 0x14ec07ddf910>> with args (<fuo_local.models.LSongModel object at 0x14ebfd6d7970>, 'hq<>') in executor
[2022-08-07 19:32:58,064 qasync._QEventLoop:34] [DEBUG]: Using default executor
[2022-08-07 19:32:58,064 qasync.QThreadExecutor:205] [DEBUG]: Submitting callback <bound method Library.song_prepare_media of <feeluown.library.library.Library object at 0x14ec07ddf910>> with args (<fuo_local.models.LSongModel object at 0x14ebfd6d7970>, 'hq<>') and kwargs {} to thread worker queue
[2022-08-07 19:32:58,065 qasync._QThreadWorker:139] [DEBUG]: #8 got callback <bound method Library.song_prepare_media of <feeluown.library.library.Library object at 0x14ec07ddf910>> with args (<fuo_local.models.LSongModel object at 0x14ebfd6d7970>, 'hq<>') and kwargs {} from queue
[2022-08-07 19:32:58,065 qasync._QThreadWorker:147] [DEBUG]: Invoking callback
[2022-08-07 19:32:58,065 qasync._QThreadWorker:154] [DEBUG]: Setting Future result: <feeluown.media.Media object at 0x14ebfd71d990>
[2022-08-07 19:32:58,066 qasync._QEventLoop:23] [DEBUG]: Running callback <bound method Library.song_upgrade of <feeluown.library.library.Library object at 0x14ec07ddf910>> with args (<fuo_local.models.LSongModel object at 0x14ebfd6d7970>,) in executor
[2022-08-07 19:32:58,066 qasync._QEventLoop:34] [DEBUG]: Using default executor
[2022-08-07 19:32:58,066 qasync.QThreadExecutor:205] [DEBUG]: Submitting callback <bound method Library.song_upgrade of <feeluown.library.library.Library object at 0x14ec07ddf910>> with args (<fuo_local.models.LSongModel object at 0x14ebfd6d7970>,) and kwargs {} to thread worker queue
[2022-08-07 19:32:58,067 qasync._QThreadWorker:139] [DEBUG]: #3 got callback <bound method Library.song_upgrade of <feeluown.library.library.Library object at 0x14ec07ddf910>> with args (<fuo_local.models.LSongModel object at 0x14ebfd6d7970>,) and kwargs {} from queue
[2022-08-07 19:32:58,067 qasync._QThreadWorker:147] [DEBUG]: Invoking callback
[2022-08-07 19:32:58,067 qasync._QThreadWorker:154] [DEBUG]: Setting Future result: fuo://local/songs/169168093
[2022-08-07 19:32:58,068 feeluown.task:85] [ERROR]: Task set-current-model failed
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/feeluown/task.py", line 81, in _cb
    future.result()
  File "/usr/lib/python3.10/site-packages/feeluown/player/playlist.py", line 453, in a_set_current_song
    metadata = await self._prepare_metadata_for_song(target_song)
  File "/usr/lib/python3.10/site-packages/feeluown/player/playlist.py", line 505, in _prepare_metadata_for_song
    metadata[MetadataFields.artwork] = artwork
  File "/usr/lib/python3.10/site-packages/feeluown/player/metadata.py", line 55, in __setitem__
    raise ValueError(f'field {field} expect {expected}, acture {type(value)}')
ValueError: field MetadataFields.artwork expect <class 'str'>, acture <class 'feeluown.media.Media'>
[2022-08-07 19:32:58,069 feeluown.player.playlist:595] [ERROR]: play model failed
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/feeluown/player/playlist.py", line 593, in cb
    future.result()
  File "/usr/lib/python3.10/site-packages/feeluown/task.py", line 81, in _cb
    future.result()
  File "/usr/lib/python3.10/site-packages/feeluown/player/playlist.py", line 453, in a_set_current_song
    metadata = await self._prepare_metadata_for_song(target_song)
  File "/usr/lib/python3.10/site-packages/feeluown/player/playlist.py", line 505, in _prepare_metadata_for_song
    metadata[MetadataFields.artwork] = artwork
  File "/usr/lib/python3.10/site-packages/feeluown/player/metadata.py", line 55, in __setitem__
    raise ValueError(f'field {field} expect {expected}, acture {type(value)}')
ValueError: field MetadataFields.artwork expect <class 'str'>, acture <class 'feeluown.media.Media'>
`

**Expected behavior**
Play the selected music.

**Desktop:**
 - OS: Gentoo
 - Version: feeluown 3.8.7

**Comment by cosven** [comment]
是本地音乐插件的兼容性问题，其它插件不存在这个问题 ~ 预计最近一两周会修复一下。

**Comment by cosven** [comment]
已经在 #616 中修复了。在 FeelUOwn 中兼容了这种特殊情况。
