### ISSUE TITLE
Archlinux下无法启动

### ISSUE THREAD

**Issue by Luyiay** [feeluown/FeelUOwn#642]
**Describe the bug**
如题

报错信息
`Traceback (most recent call last):
  File "/sbin/feeluown", line 33, in <module>
    sys.exit(load_entry_point('feeluown==3.8.9', 'console_scripts', 'feeluown')())
  File "/sbin/feeluown", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3.10/site-packages/feeluown/__main__.py", line 6, in <module>
    from feeluown.entry_points.run import run
  File "/usr/lib/python3.10/site-packages/feeluown/entry_points/run.py", line 15, in <module>
    from .run_cli import run_cli  # noqa: E402
  File "/usr/lib/python3.10/site-packages/feeluown/entry_points/run_cli.py", line 2, in <module>
    from feeluown.cli import climain
  File "/usr/lib/python3.10/site-packages/feeluown/cli/__init__.py", line 1, in <module>
    from .cli import climain, oncemain  # noqa
  File "/usr/lib/python3.10/site-packages/feeluown/cli/cli.py", line 8, in <module>
    from feeluown.library import fmt_artists_names
  File "/usr/lib/python3.10/site-packages/feeluown/library/__init__.py", line 2, in <module>
    from .library import Library
  File "/usr/lib/python3.10/site-packages/feeluown/library/library.py", line 14, in <module>
    from .provider_v2 import ProviderV2
  File "/usr/lib/python3.10/site-packages/feeluown/library/provider_v2.py", line 5, in <module>
    from .models import V2SupportedModelTypes
  File "/usr/lib/python3.10/site-packages/feeluown/library/models.py", line 57, in <module>
    from pydantic import BaseModel as _BaseModel, PrivateAttr
  File "pydantic/__init__.py", line 2, in init pydantic.__init__
  File "pydantic/dataclasses.py", line 39, in init pydantic.dataclasses
    # Key:
ImportError: cannot import name dataclass_transform
`

**Desktop:**
 - OS: Archlinux Kernel: x86_64 Linux 6.1.1-arch1-1
 - Version: [e.g. feeluown 3.3.6]

**Comment by cosven** [comment]
我在 Arch 下没有复现这个问题。我把包都升级到了最新版本（`yay -Syu`），也没有复现。

看了下报错信息，我 **怀疑** 大概率是部分 Python 依赖包（比如 `typing_extention`，对应的 arch 包是 `python-typing-extensions`）被手动卸载了。可以尝试运行下面这个命令来确认一下，如果运行失败了，则基本可以实锤是上述原因。如果能运行运行成功，那么则需要更多信息来辅助定位问题的原因。
```
python3 -c "import typing_extensions"
```

如果确实是上述原因导致的，可以尝试手动重新安装 `python-typing-extensions` 包（如运行命令 `yay -Sy python-typing-extensions`）。

**Comment by Luyiay** [comment]
> 我在 Arch 下没有复现这个问题。我把包都升级到了最新版本（`yay -Syu`），也没有复现。
> 
> 看了下报错信息，我 **怀疑** 大概率是部分 Python 依赖包（比如 `typing_extention`，对应的 arch 包是 `python-typing-extensions`）被手动卸载了。可以尝试运行下面这个命令来确认一下，如果运行失败了，则基本可以实锤是上述原因。如果能运行运行成功，那么则需要更多信息来辅助定位问题的原因。
> 
> ```
> python3 -c "import typing_extensions"
> ```
> 
> 如果确实是上述原因导致的，可以尝试手动重新安装 `python-typing-extensions` 包（如运行命令 `yay -Sy python-typing-extensions`）。

该命令没有报错，今天重新安装feeluown后自己就好了
