### ISSUE TITLE
feeluown windows 打包缺少 ytmusicapi 相关文件

### ISSUE THREAD

**Issue by cosven** [feeluown/FeelUOwn#748]
**问题**

branch-3.8.x 分支打出来的包，windows 上会遇到这样的问题
```
Traceback (most recent call last):
  File "feeluown\gui\widgets\login.py", line 161, in login
  File "feeluown\gui\widgets\login.py", line 171, in login_with_cookies
  File "fuo_ytmusic\ui.py", line 134, in setup_user
  File "fuo_ytmusic\provider.py", line 50, in user
  File "fuo_ytmusic\service.py", line 211, in reload
  File "fuo_ytmusic\service.py", line 203, in _initialize_by_headerfile
  File "ytmusicapi\ytmusic.py", line 163, in init
  File "gettext.py", line 592, in translation
FileNotFoundError: [Errno 2] No translation file found for domain: 'base'

        locale_dir = os.path.abspath(os.path.dirname(__file__)) + os.sep + "locales"
        self.lang = gettext.translation("base", localedir=locale_dir, languages=[language])
```

**解决方案**
https://github.com/feeluown/FeelUOwn/blob/b28383856aba7e362b0e6c3dae0a028bcf647218/pyinstaller_hooks/hook-feeluown.py#L26-L30

可能是这里还需要加一行类似

collect_data_files('ytmusicapi', ....)

**Comment by cosven** [comment]
@cosven 如果能有空研究一下 pyinstaller 打包后是否能使用 pip/python 就更好了

**Comment by poly000** [comment]
或者 **/*.mo, **/*.po ？

**Comment by cosven** [comment]
> 或者 **/*.mo, **/*.po ？

看起来 .po 文件就够了 ~
https://github.com/sigma67/ytmusicapi/blob/dcddfa562bd6deeeb3cdcb1df7955dab27817c0a/pyproject.toml#L37
