### ISSUE TITLE
好像不支持mpv 0.38

### ISSUE THREAD

**Issue by orzogc** [feeluown/FeelUOwn#823]
**Describe the bug**
mpv升级到0.38后无法播放歌曲

log:
```plain
[2024-04-19 19:03:32,557 qasync._QEventLoop:739] [ERROR]: Task exception was never retrieved
future: <Task finished name='Task-19' coro=<TableContainer._on_songs_table_activated() done, defined at /usr/lib/python3.11/site-packages/feeluown/gui/page_containers/table.py:480> exception=ValueError('Invalid value for mpv parameter', -4, (<MpvHandle object at 0x79aa941cbe30>, <feeluown.mpv.c_char_p_Array_5 object at 0x79aa8963a060>))>
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/feeluown/gui/page_containers/table.py", line 499, in _on_songs_table_activated
    self._app.playlist.play_model(song)
  File "/usr/lib/python3.11/site-packages/feeluown/player/playlist.py", line 725, in play_model
    self._app.player.stop()
  File "/usr/lib/python3.11/site-packages/feeluown/player/mpvplayer.py", line 241, in stop
    self.play(None)
  File "/usr/lib/python3.11/site-packages/feeluown/player/mpvplayer.py", line 111, in play
    self._stop_mpv()
  File "/usr/lib/python3.11/site-packages/feeluown/player/mpvplayer.py", line 276, in _stop_mpv
    self._mpv.play("")
  File "/usr/lib/python3.11/site-packages/feeluown/mpv.py", line 1613, in play
    self.loadfile(filename)
  File "/usr/lib/python3.11/site-packages/feeluown/mpv.py", line 1157, in loadfile
    self.command('loadfile', filename.encode(fs_enc), mode, MPV._encode_options(options))
  File "/usr/lib/python3.11/site-packages/feeluown/mpv.py", line 1049, in command
    _mpv_command(self.handle, (c_char_p*len(args))(*args))
  File "/usr/lib/python3.11/site-packages/feeluown/mpv.py", line 152, in raise_for_ec
    raise ex(ec, *args)
ValueError: ('Invalid value for mpv parameter', -4, (<MpvHandle object at 0x79aa941cbe30>, <feeluown.mpv.c_char_p_Array_5 object at 0x79aa8963a060>))
```

**To Reproduce**
1. 升级mpv到0.38
2. 启动feeluown
3. 选择一首歌曲播放

**Expected behavior**
正常播放歌曲

**Desktop:**
 - OS: Arch Linux
 - Version: feeluown 4.1.2

**Comment by cosven** [comment]
正在修复中
