### ISSUE TITLE
从 archlinuxcn 安装 feeluown-git 报错

### ISSUE THREAD

**Issue by g1fts** [feeluown/FeelUOwn#859]
```shell
Traceback (most recent call last):
  File "/usr/bin/feeluown", line 33, in <module>
    sys.exit(load_entry_point('feeluown==4.1.6', 'console_scripts', 'feeluown')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/feeluown", line 25, in importlib_load_entry_point
    return next(matches).load()
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/metadata/__init__.py", line 205, in load
    module = import_module(match.group('module'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/usr/lib/python3.12/site-packages/feeluown/__main__.py", line 6, in <module>
    from feeluown.entry_points.run import run
  File "/usr/lib/python3.12/site-packages/feeluown/entry_points/run.py", line 4, in <module>
    patch_mutagen()
  File "/usr/lib/python3.12/site-packages/feeluown/utils/patch.py", line 71, in patch_mutagen
    from mutagen.id3 import _specs
ModuleNotFoundError: No module named 'mutagen'
```

安装 `python-mutagen`之后打开再次报错

```shell
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/feeluown/utils/patch.py", line 115, in patch_pydantic
    import pydantic.v1
ModuleNotFoundError: No module named 'pydantic'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/feeluown", line 33, in <module>
    sys.exit(load_entry_point('feeluown==4.1.6', 'console_scripts', 'feeluown')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/feeluown", line 25, in importlib_load_entry_point
    return next(matches).load()
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/metadata/__init__.py", line 205, in load
    module = import_module(match.group('module'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/usr/lib/python3.12/site-packages/feeluown/__main__.py", line 6, in <module>
    from feeluown.entry_points.run import run
  File "/usr/lib/python3.12/site-packages/feeluown/entry_points/run.py", line 5, in <module>
    patch_pydantic()
  File "/usr/lib/python3.12/site-packages/feeluown/utils/patch.py", line 117, in patch_pydantic
    import pydantic
ModuleNotFoundError: No module named 'pydantic'
```

安装`python-pydantic`打开再次报错

```shell
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/feeluown/plugin.py", line 218, in _scan_entry_points
    module = entry_point.load()
             ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/metadata/__init__.py", line 205, in load
    module = import_module(match.group('module'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/usr/lib/python3.12/site-packages/feeluown/local/__init__.py", line 7, in <module>
    from .provider_ui import LocalProviderUi
  File "/usr/lib/python3.12/site-packages/feeluown/local/provider_ui.py", line 6, in <module>
    from .ui import LibraryRenderer
  File "/usr/lib/python3.12/site-packages/feeluown/local/ui.py", line 2, in <module>
    from feeluown.gui.page_containers.table import Renderer
  File "/usr/lib/python3.12/site-packages/feeluown/gui/page_containers/table.py", line 20, in <module>
    from feeluown.gui.components import SongMenuInitializer
  File "/usr/lib/python3.12/site-packages/feeluown/gui/components/__init__.py", line 13, in <module>
    from .collections import CollectionListView  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/feeluown/gui/components/collections.py", line 7, in <module>
    from feeluown.collection import CollectionType, Collection
  File "/usr/lib/python3.12/site-packages/feeluown/collection.py", line 9, in <module>
    import tomlkit
ModuleNotFoundError: No module named 'tomlkit'
QFont::fromString: Invalid description 'Noto Sans CJK SC,12,-1,5,400,0,0,0,0,0,0,0,0,0,0,1'
QFont::fromString: Invalid description 'JetBrains Mono,12,-1,5,400,0,0,0,0,0,0,0,0,0,0,1'
QFont::fromString: Invalid description 'Noto Sans CJK SC,12,-1,5,400,0,0,0,0,0,0,0,0,0,0,1'
QFont::fromString: Invalid description 'Noto Sans CJK SC,12,-1,5,400,0,0,0,0,0,0,0,0,0,0,1'
Traceback (most recent call last):
  File "/usr/bin/feeluown", line 33, in <module>
    sys.exit(load_entry_point('feeluown==4.1.6', 'console_scripts', 'feeluown')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/feeluown/entry_points/run.py", line 38, in run
    return run_app(args)
           ^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/feeluown/entry_points/run_app.py", line 28, in run_app
    runner.run(start_app(args, config))
  File "/usr/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/qasync/__init__.py", line 409, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/feeluown/entry_points/run_app.py", line 101, in start_app
    app = create_app(args, config)
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/feeluown/app/app.py", line 298, in create_app
    from feeluown.app.mixed_app import MixedApp
  File "/usr/lib/python3.12/site-packages/feeluown/app/mixed_app.py", line 2, in <module>
    from .gui_app import GuiApp
  File "/usr/lib/python3.12/site-packages/feeluown/app/gui_app.py", line 14, in <module>
    from feeluown.gui.ui import Ui
  File "/usr/lib/python3.12/site-packages/feeluown/gui/ui.py", line 5, in <module>
    from feeluown.gui.widgets.settings import SettingsDialog
  File "/usr/lib/python3.12/site-packages/feeluown/gui/widgets/settings.py", line 7, in <module>
    from feeluown.gui.components import LyricButton, WatchButton
  File "/usr/lib/python3.12/site-packages/feeluown/gui/components/__init__.py", line 13, in <module>
    from .collections import CollectionListView  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/feeluown/gui/components/collections.py", line 7, in <module>
    from feeluown.collection import CollectionType, Collection
  File "/usr/lib/python3.12/site-packages/feeluown/collection.py", line 9, in <module>
    import tomlkit
ModuleNotFoundError: No module named 'tomlkit'
```

安装`python-tomlkit`之后就可以正常打开了。

**Comment by g1fts** [comment]
不知道下面这段算不算有错误
```shell
QFont::fromString: Invalid description 'Noto Sans CJK SC,12,-1,5,400,0,0,0,0,0,0,0,0,0,0,1'
QFont::fromString: Invalid description 'JetBrains Mono,12,-1,5,400,0,0,0,0,0,0,0,0,0,0,1'
QFont::fromString: Invalid description 'Noto Sans CJK SC,12,-1,5,400,0,0,0,0,0,0,0,0,0,0,1'
QFont::fromString: Invalid description 'Noto Sans CJK SC,12,-1,5,400,0,0,0,0,0,0,0,0,0,0,1'
[2024-08-01 22:44:08,641 feeluown.version:37] [WARNING]: HTTPSConnectionPool(host='pypi.org', port=443): Read timed out. (read timeout=2)
[2024-08-01 22:44:08,642 feeluown.version:38] [WARNING]: 检查更新失败
```

**Comment by g1fts** [comment]
另外点全部播放无反应，控制台得到如下提示
```shell
[2024-08-01 22:56:22,921 feeluown.task:85] [ERROR]: Task play-all failed
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/feeluown/task.py", line 81, in _cb
    future.result()
  File "/usr/lib/python3.12/site-packages/qasync/__init__.py", line 145, in run
    r = callback(*args, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/feeluown/utils/reader.py", line 173, in readall
    list(self)
  File "/usr/lib/python3.12/site-packages/feeluown/utils/reader.py", line 98, in __next__
    return self._read_next()
           ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/feeluown/utils/reader.py", line 192, in _read_next
    obj = next(self._g)
          ^^^^^^^^^^^^^
ValueError: generator already executing
```

**Comment by cosven** [comment]
第一个问题：要安装若干个包才可以用。

这个是因为 feeluown-git 包很久没更新了，欠缺很多依赖。一个比较简易的解决办法是先安装 feeluown 包，这个包的依赖是全的，然后再安装 feeluown-git 替换 feeluown。当然也可以直接使用 feeluown。

> 另外点全部播放无反应，控制台得到如下提示

搜索歌曲、播放单首歌曲，可以用么？

**Comment by g1fts** [comment]
> 第一个问题：要安装若干个包才可以用。
> 
> 这个是因为 feeluown-git 包很久没更新了，欠缺很多依赖。一个比较简易的解决办法是先安装 feeluown 包，这个包的依赖是全的，然后再安装 feeluown-git 替换 feeluown。当然也可以直接使用 feeluown。
> 
> > 另外点全部播放无反应，控制台得到如下提示
> 
> 搜索歌曲、播放单首歌曲，可以用么？

我装之前特地看了下版本，archlinuxcn源的版本跟上了的，aur的没有。
单曲播放没问题，搜索没试过。估计够呛，因为上面的报错里有首页提示网络无法连接的。
我回头就去下普通包🥳
